SYNTHS = [
    'dull_bell',
    'pretty_bell',
    'beep',
    'sine',
    'saw',
    'pulse',
    'subpulse',
    'square',
    'tri',
    'dsaw',
    'dpulse',
    'dtri',
    'fm',
    'mod_fm',
    'mod_saw',
    'mod_dsaw',
    'mod_sine',
    'mod_beep',
    'mod_tri',
    'mod_pulse',
    'chiplead',
    'chipbass',
    'tb303',
    'supersaw',
    'hoover',
    'prophet',
    'zawa',
    'dark_ambience',
    'growl',
    'hollow',
    'blade',
    'piano',
    'pluck',
    'tech_saws',
]


TONICS = [
    'a0',
    'b0',
    'c1',
    'd1',
    'e1',
    'f1',
    'g1',
]


SCALES = {
    'diatonic': 0,
    'ionian': 0,
    'major': 0,
    'dorian': 0,
    'phrygian': 0,
    'lydian': 0,
    'mixolydian': 0,
    'aeolian': 0,
    'minor': 0,
    'locrian': 0,
    'hex_major6': 0,
    'hex_dorian': 0,
    'hex_phrygian': 0,
    'hex_major7': 0,
    'hex_sus': 0,
    'hex_aeolian': 0,
    'minor_pentatonic': 0,
    'yu': 0,
    'major_pentatonic': 0,
    'gong': 0,
    'egyptian': 0,
    'shang': 0,
    'jiao': 0,
    'zhi': 0,
    'ritusen': 0,
    'whole_tone': 0,
    'whole': 0,
    'chromatic': 0,
    'harmonic_minor': 0,
    'melodic_minor_asc': 0,
    'hungarian_minor': 0,
    'octatonic': 0,
    'messiaen1': 0,
    'messiaen2': 0,
    'messiaen3': 0,
    'messiaen4': 0,
    'messiaen5': 0,
    'messiaen6': 0,
    'messiaen7': 0,
    'super_locrian': 0,
    'hirajoshi': 0,
    'kumoi': 0,
    'neapolitan_major': 0,
    'bartok': 0,
    'bhairav': 0,
    'locrian_major': 0,
    'ahirbhairav': 0,
    'enigmatic': 0,
    'neapolitan_minor': 0,
    'pelog': 0,
    'augmented2': 0,
    'scriabin': 0,
    'harmonic_major': 0,
    'melodic_minor_desc': 0,
    'romanian_minor': 0,
    'hindu': 0,
    'iwato': 0,
    'melodic_minor': 0,
    'diminished2': 0,
    'marva': 0,
    'melodic_major': 0,
    'indian': 0,
    'spanish': 0,
    'prometheus': 0,
    'diminished': 0,
    'todi': 0,
    'leading_whole': 0,
    'augmented': 0,
    'purvi': 0,
    'chinese': 0,
    'lydian_minor': 0,
    'blues_major': 0,
    'blues_minor': 0,
}
