BoxLayout:
	orientation: 'vertical'
	samples_groups: samples_carousel

	BoxLayout:
		orientation: 'horizontal'
		size_hint_y: 0.15

		Button:
			text: "<="
			size_hint_x: 0.1
			on_press: root.samples_groups.load_previous()
		Label:
			text: 'Samples'
			size_hint_x: 0.8
		Button:
			text: "=>"
			size_hint_x: 0.1
			on_press: root.samples_groups.load_next()

	SamplesCarousel:
		id: samples_carousel
		size_hint_y: 0.85


<PlayButton>:
	on_press: self.play()
