SYNTHS = [
    'dull_bell',
    'pretty_bell',
    'beep',
    'sine',
    'saw',
    'pulse',
    'subpulse',
    'square',
    'tri',
    'dsaw',
    'dpulse',
    'dtri',
    'fm',
    'mod_fm',
    'mod_saw',
    'mod_dsaw',
    'mod_sine',
    'mod_beep',
    'mod_tri',
    'mod_pulse',
    'chiplead',
    'chipbass',
    'tb303',
    'supersaw',
    'hoover',
    'prophet',
    'zawa',
    'dark_ambience',
    'growl',
    'hollow',
    'blade',
    'piano',
    'pluck',
    'tech_saws',
]


TONICS = [
    'a0',
    'a#0',
    'b0',
    'c1',
    'c#1',
    'd1',
    'd#1',
    'e1',
    'f1',
    'f#1',
    'g1',
    'g#1',
]


SCALES = {
    'diatonic': 7,
    'ionian': 7,
    'major': 7,
    'dorian': 7,
    'phrygian': 7,
    'lydian': 7,
    'mixolydian': 7,
    'aeolian': 7,
    'minor': 7,
    'locrian': 7,
    'hex_major6': 6,
    'hex_dorian': 6,
    'hex_phrygian': 6,
    'hex_major6': 6,
    'hex_sus': 6,
    'hex_aeolian': 6,
    'minor_pentatonic': 5,
    'yu': 5,
    'major_pentatonic': 5,
    'gong': 5,
    'egyptian': 5,
    'shang': 5,
    'jiao': 5,
    'zhi': 5,
    'ritusen': 5,
    'whole_tone': 6,
    'whole': 6,
    'chromatic': 12,
    'harmonic_minor': 7,
    'melodic_minor_asc': 7,
    'hungarian_minor': 7,
    'octatonic': 8,
    'messiaen1': 6,
    'messiaen2': 8,
    'messiaen3': 9,
    'messiaen4': 8,
    'messiaen5': 6,
    'messiaen6': 8,
    'messiaen7': 10,
    'super_locrian': 7,
    'hirajoshi': 5,
    'kumoi': 5,
    'neapolitan_major': 7,
    'bartok': 7,
    'bhairav': 7,
    'locrian_major': 7,
    'ahirbhairav': 7,
    'enigmatic': 7,
    'neapolitan_minor': 7,
    'pelog': 5,
    'augmented2': 6,
    'scriabin': 5,
    'harmonic_major': 7,
    'melodic_minor_desc': 7,
    'romanian_minor': 7,
    'hindu': 7,
    'iwato': 5,
    'melodic_minor': 7,
    'diminished2': 8,
    'marva': 7,
    'melodic_major': 7,
    'indian': 5,
    'spanish': 7,
    'prometheus': 5,
    'diminished': 8,
    'todi': 7,
    'leading_whole': 7,
    'augmented': 6,
    'purvi': 7,
    'chinese': 5,
    'lydian_minor': 7,
    'blues_major': 6,
    'blues_minor': 6,
}
